VERSION 0.7

deps:
    FROM ../../+devshell
    WORKDIR /work

    COPY package.json package-lock.json .
    RUN with_nix npm ci

check:
    FROM +deps

    COPY --dir src .
    COPY .eslintrc.yml tsconfig.json .

    RUN with_nix npm run format:check
    RUN with_nix npm run lint
    RUN with_nix npm test

package:
    FROM +check

    RUN with_nix npm run package

    SAVE ARTIFACT dist dist AS LOCAL dist

check-dist:
    FROM +check

    COPY --dir dist dist_old
    RUN with_nix npm run package
    RUN diff -r dist_old dist