name: "Run"
description: "Runs an Earthly target"
inputs:
  artifact:
    description: The name of the artifact to export
    required: false
  earthfile:
    description: The path to the Earthfile containing the target to run
    required: true
  flags:
    description: Additional flags to pass to the Earthly CLI
    required: false
  target:
    description: The name of the target to run
    required: true
runs:
  using: "node20"
  main: "dist/index.js"
